apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label 
    run: hellopod1
  name: hellopod1 # name of pod 
spec:
  volumes: # to create volumes 
  - name: ashuvol1 # name of volume  
    emptyDir: {} # it will take space from  scheduled minion node automatically 
  containers:
  - image: nginx 
    name: ashuc1 
    volumeMounts:
    - name: ashuvol1
      mountPath: /usr/share/nginx/html/
      readOnly: True 
  - image: alpine # image from docker hub 
    name: hellopod1 # name of container 
    volumeMounts:
    - name: ashuvol1 # same volume we created above 
      mountPath: /mnt/oracle/ # this location inside cont will be created 
    command: ["sh","-c","while true;do date >>/mnt/oracle/time.txt;sleep 5;done"] # replacing entrypoint process of docker img
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
