apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label of pod 
    run: webapp2
  name: webapp2 # name of pod 
spec:
  containers:
  - image: dockerashu/ashuoracleweb:v111
    name: webapp2
    ports:
    - containerPort: 80
    env: # app3 want to host 
    - name: deploy
      value: app3 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc2
  name: ashusvc2
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # pod finder 
    run: webapp2 # this is label of POD 
  type: NodePort
status:
  loadBalancer: {}
