apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc1
  name: ashusvc1 # name of service 
spec:
  ports:
  - name: 1234-80
    port: 1234 # service port that will be bounded with service IP
    protocol: TCP
    targetPort: 80 # pod app port number 
  selector: # we need to give exactly same label what pod has
    run: webapp1 # label of POD 
  type: NodePort # type of service 
status:
  loadBalancer: {}
